#Login
xuser = "//input[@id='admintentruycap']"
xpw = "//input[@id='adminmatkhau']"
btnlogin ="//button[contains(text(),'ĐĂNG NHẬP')]"
#liên hệ
xhovaten = "//input[@id='s_fullname']"
xsdt = "//input[@id='s_dienthoai']"
xemail = "//input[@id='s_email']"
xdiachi = "//input[@id='s_address']"
xtieude = "//input[@id='s_title']"
xnoidung = "//textarea[@id='s_message']"
xmbv = "//input[@id='mabaove']"
xgui = "//a[contains(text(),'Gửi')]"
xlamlai = "//a[contains(text(),'Làm lại')]"
xcaptcha = "//img[@id='img_contact_cap']"